### ISSUE TITLE
Golden / Admin chat isn't replicated on both clients.

### ISSUE THREAD

**Issue by CitizenFoffie** [p0s0/ob-framework#14]
**Describe the bug**
When you make a admin have the yellow chat other players don't see the yellow chat

**Comment by CitizenFoffie** [comment]
possible fix added to my branch by turning "~= nil" to "== true"
why this works no idea, but it does

**Comment by Cristiano100** [comment]
Unable to reproduce

**Comment by p0s0** [comment]
Unable to reproduce this issue. Closing
