### ISSUE TITLE
Framework Bug - gui disappearing when i set a custom game id in set.LeaveTeleportId on 2014L-2016L

### ISSUE THREAD

**Issue by Rxplicat3dStxr4ge** [p0s0/ob-framework#17]
ok. like. what the fuck. 
![BRUH MOMENT](https://user-images.githubusercontent.com/99167692/155088796-01f741c4-7555-4ffd-b235-7a8b33ce4aad.png)
.

i've tried fixes that i could think of, but they are impossible.

**Comment by Rxplicat3dStxr4ge** [comment]
Steps to reproduce:

Install the module into the game like normal

Go into the module, and Global, ReplicatedStorage, and look for OB_Services. then go into GlobalSettings and scroll down. Change the set.LeaveTeleportId into any custom game id, then after that, playtest the game.

**Comment by Rxplicat3dStxr4ge** [comment]
The thing is, this bug occured ever since 1.5.1 (iirc)

**Comment by CitizenFoffie** [comment]
Try before 1.5.1 and see if the bug is still there

**Comment by Rxplicat3dStxr4ge** [comment]
ok

**Comment by Rxplicat3dStxr4ge** [comment]
the gui no longer disappears, but when i leave it says "Attempt to teleport to a place that is restricted" despite the fact that i set it to one of my games that are public

https://user-images.githubusercontent.com/99167692/155471451-9f56b11a-8a4e-49eb-873f-302966bd6f61.mp4

.

**Comment by Rxplicat3dStxr4ge** [comment]
i'm using ob framework 1.5 btw

**Comment by p0s0** [comment]
Try using ob-framework v1.6, is the bug still occurring? Make sure that you're also using Places instead of separate Games, which can be done with the [Asset Manager](https://developer.roblox.com/en-us/resources/studio/Asset-Manager) inside of Roblox Studio. I cannot reproduce this.

**Comment by Cristiano100** [comment]
what’s with all these wacky labels

**Comment by p0s0** [comment]
> what’s with all these wacky labels

(trying) to keep as organized as i can

**Comment by Rxplicat3dStxr4ge** [comment]
i'm not using seperate games

**Comment by Rxplicat3dStxr4ge** [comment]
oh wow i fixed it lmao
