### ISSUE TITLE
BubbleChat for pre-2015.

### ISSUE THREAD

**Issue by CitizenFoffie** [p0s0/ob-framework#36]
Here's the RBXM of the BubbleChat gui, all you would need to do is some tweaking to get it into the player and make it look good on a Billboard GUI, I've been trying to get this feature to work by myself but I'm throwing in the towel because I can't get Chatted working.
https://www.roblox.com/library/9460429955/2010-2015

**Comment by CitizenFoffie** [comment]
![image](https://user-images.githubusercontent.com/40131823/165012003-2f46a6b2-c227-4061-9719-d4d63a6b4a88.png)
I made it work here's my mainmodule(only for my custom 2012M)
https://www.roblox.com/library/9462352170/MainModule2012M
Code that fires it: 
```
wait(.1)
local thing = script.Parent.Parent.ChatFrame.ChatRenderFrame
local name
local msg
function trim(s)
	return (s:gsub("^%s*(.-)%s*$", "%1"))
end
--print(script.Parent.RemoteEvent.Name)
thing.ChildAdded:Connect(function(child)
	if string.find(child.Name, "message") then
		wait(0.1)
		local split = string.split(child.Name," - ")
		name = thing:FindFirstChild(split[1])
		msg = child.Text
		local box = child:Clone() --anything from here to senderp you can delete
		box.Parent = child
		box.Position = UDim2.new(-0.01,0,0,0)
		box.Text = name.Text..trim(msg)
		box.TextXAlignment = Enum.TextXAlignment.Left
		box.TextYAlignment = Enum.TextYAlignment.Top
		box.Size = UDim2.new(0,box.TextBounds.X + 24,0,box.TextBounds.Y + 1)
		box.Name = name.Text..trim(msg)
		box.TextTransparency = 1
		box.ZIndex = -1
		box.BackgroundTransparency = 0.3
		print(thing:FindFirstChild(split[1]))
		local senderp = game.Players:FindFirstChild(game.Players.LocalPlayer.Name) -- you can remove everything above this if its not 2012
		print(senderp)
		if senderp then
			print("SENDERP")
			if senderp.Character then
				if senderp.Character:FindFirstChild("Head") then
					
					local texttosend = string.split(name.Text..trim(msg),";")
					print(texttosend[2])
					wait(0)
					game.ReplicatedStorage.OB_Events.OB_ChatBubble:FireServer(senderp,texttosend[2])
				end
			end
		end
	end
end)
```

**Comment by CitizenFoffie** [comment]
dont use this at all actually it breaks if its not 2012M

**Comment by CitizenFoffie** [comment]
ok fixed it up https://www.roblox.com/library/9462352170/MainModule2012M?ViewInBrowser=true&CreatorId=391697074&SearchId=06BBBBC6-F821-4DAB-A16D-E9899439CA22&Category=Model&Position=1&SearchKeyword=&CreatorType=User&SortType=Relevance
(right now it only supports 2014E but if you put the background script inside chatscript it'll work all the same)

**Comment by Rxplicat3dStxr4ge** [comment]
hippity hoppity your 2012M of ob framework module is now my property
