### ISSUE TITLE
Chat doesn't censor(almost all Periods)

### ISSUE THREAD

**Issue by CitizenFoffie** [p0s0/ob-framework#37]
![image](https://user-images.githubusercontent.com/40131823/165382085-449d38bc-1131-44a0-8c8a-c1f2366cee17.png)

**Comment by CitizenFoffie** [comment]
Could be it only filters for the client not the sender.

**Comment by p0s0** [comment]
It does censor. It doesn't censor messages for the sender, though. Other players see the filtered message. This is allowed by Roblox.
