### ISSUE TITLE
Lack of accurate chat features

### ISSUE THREAD

**Issue by CitizenFoffie** [p0s0/ob-framework#38]
Expected behavior: chat commands for 2014E and 2014M.
![image](https://user-images.githubusercontent.com/40131823/165638127-cf987d6e-7c9f-413f-b9d8-2b259d3b2d85.png)
Bug/Unimplemented feature, they dont work.
Also menu chat should exist for 2014E, I think the chat scripts of the period had code for them but its either toggled out or the corescript isn't soon enough.

**Comment by p0s0** [comment]
Menu chat should exist. I have yet to implement this. The behavior is normal, however. There are no chat commands (as far as I know) other than emote commands.
