### ISSUE TITLE
Framework Bug - [BUG]

### ISSUE THREAD

**Issue by CitizenFoffie** [p0s0/ob-framework#5]
**Describe the bug**
The username on the top right is the name of the player who joined the newest.
![image](https://user-images.githubusercontent.com/40131823/147991865-824a7fd9-2a9d-4017-81b9-4b3465be2e4a.png)

**Comment by CitizenFoffie** [comment]
(2014M)

**Comment by Cristiano100** [comment]
Can't reproduce on latest release, only on the release this issue was opened on. If it was fixed please close it.

**Comment by p0s0** [comment]
Can't reproduce.
