### ISSUE TITLE
Vehicle Seat cars don't move

### ISSUE THREAD

**Issue by CitizenFoffie** [p0s0/ob-framework#6]
**Describe the bug**
I can't drive vehicle seat cars anymore
**To Reproduce**
Go into a car and try and drive.
**Expected behavior**
To drive.

**Screenshots**
![image](https://user-images.githubusercontent.com/40131823/147992083-4f216397-4448-4cbb-bad8-801f0bdb7934.png)

**Comment by CitizenFoffie** [comment]
(2014M)

**Comment by CitizenFoffie** [comment]
this applies to all versions

**Comment by p0s0** [comment]
this is a known issue, after 1.6 releases i'll work on it

**Comment by CitizenFoffie** [comment]
Fixed with Cristano's pull request.

**Comment by p0s0** [comment]
can confirm
