### ISSUE TITLE
Can't disable shift lock?

### ISSUE THREAD

**Issue by CitizenFoffie** [p0s0/ob-framework#7]
I can't disable shift lock with both the fake game menu and the real one.

**Comment by CitizenFoffie** [comment]
(2014M)

**Comment by p0s0** [comment]
Hey, I need more information about this. Can you provide a video/screenshot?

**Comment by CitizenFoffie** [comment]
Basically no matter what the shift lock does not disable and is always on.
https://medal.tv/games/roblox-studio/clips/7xzezkwW42wM_/d1337AcIyUAE?invite=cr-MSxuZlEsMzgyMzc0ODYs

**Comment by p0s0** [comment]
Yeah, I can see the issue here. I'll see what I can do right now.

**Comment by p0s0** [comment]
Fixed in v1.5.1
